### ISSUE TITLE
issues with 

### ISSUE THREAD

**Issue by bdickenson** [OH-Jython-Scripters/openhab2-jython#9] opened 2017-12-08 17:48 UTC
Well, @spacemanspiff2007 and @steve-bate , I am not sure issue #8  should be closed. I am seeing the same symptom and I have extensive items defined in .items files. Do these have to be otherwise exposed to jython ?

Running a standalone jython 2.7.1 on RPi3. Latest (or near-latest) dev build of OH2 running under Openhabian. (NB the jython 2.7.1 full distro does not install correctly on RPi3 -- fails on setuptools installation). I have following defined in /etc/default/openhab2:

EXTRA_JAVA_OPTS="-Xbootclasspath/a:/home/openhabian/jython2.7.1/jython.jar
-Dpython.home=/etc/openhab2/lib/python/:/etc/openhab2/automation/jsr223/
-Dpython.path=/etc/openhab2/lib/python/:/etc/openhab2/automation/jsr223/
-Djython.path=/etc/openhab2/lib/python/:/etc/openhab2/automation/jsr223/ "

**Comment by steve-bate** [comment] 2017-12-09 11:23
Unfortunately, I'm not going to have the time in the near future to do any deep investigation on this. It would help if we could diagnose whether the issue is in the ESH core or not. @bdickenson, can you reproduce this problem with a simple Jython script (no openhab2-jython)? @spacemanspiff2007, what caused you to suggest adding items to fix the problem? Thanks in advance for any assistance you can provide.

**Comment by openhab-5iver** [comment] 2018-10-01 09:30
@bdickenson , I'm doing some cleanup of this repo in preparation for bringing the modules up to date in order to work with the current ESH Automation API. I'm going to close this issue do to its age, but it can be reopened if it still occurs with in a recent version of OH.

**Closed by openhab-5iver** 2018-10-01 09:30 UTC
