### ISSUE TITLE
Error importing triggers

### ISSUE THREAD

**Issue by sim0nx** [OH-Jython-Scripters/openhab2-jython#22] opened 2018-10-06 16:46 UTC
Hi,

I am trying to write a new rule, based on an example I found here.
Openhab version: 
> ii  openhab2                              2.3.0-1
> EXTRA_JAVA_OPTS="-Xbootclasspath/a:/opt/jython/jython.jar -Dpython.home=/opt/jython -Dpython.path=/etc/openhab2/automation/lib/python"

Rule extension is loaded:
> [INFO ] [.internal.GenericScriptEngineFactory] - Activated scripting support for python

Simply importing:
> from openhab.triggers import StartupTrigger

Gives the following error:
> ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/modes.py': ImportError: No module named core in <script> at line number 2

openhab module is correctly installed:
>ls -l /etc/openhab2/automation/lib/python/openhab/
>total 44
>-rw-r--r-- 1 root root  212 Oct  6 17:05 __init__.py
>-rw-r--r-- 1 root root  465 Oct  6 17:05 actions.py
>-rw-r--r-- 1 root root 2789 Oct  6 17:05 date.py
>-rw-r--r-- 1 root root  659 Oct  6 17:05 items.py
>-rw-r--r-- 1 root root 2024 Oct  6 17:05 jsr223.py
>-rw-r--r-- 1 root root 1287 Oct  6 17:05 log.py
>drwxr-xr-x 2 root root 4096 Oct  6 17:05 osgi
>-rw-r--r-- 1 root root 1393 Oct  6 17:05 rules.py
>-rw-r--r-- 1 root root 2331 Oct  6 17:05 testing.py
>-rw-r--r-- 1 root root 8074 Oct  6 17:05 triggers.py

Removing the import and just doing a simple:
> from org.slf4j import LoggerFactory
> LoggerFactory.getLogger("org.eclipse.smarthome.automation.examples").info("Hello world!")

works correctly.
Importing openhab.rules works as well:
> from openhab.rules import rule, addRule

Any ideas or how I could debug this ?

Thank you

**Comment by openhab-5iver** [comment] 2018-10-06 18:46
> I am trying to write a new rule, based on an example I found here.

Since you are on 2.3, you will need to use the files from the original branch. I _just_ merged in a number of changes into master. It would be best if you were on at least the latest milestone release due to significant changes in the Automation API. 

Have you tried another script for testing? Try this one...
```
from org.slf4j import Logger, LoggerFactory
scriptExtension.importPreset("RuleSupport")
scriptExtension.importPreset("RuleSimple")
log = LoggerFactory.getLogger("org.eclipse.smarthome.model.script.Rules")

class MyRule(SimpleRule):
    def __init__(self):
        self.triggers = [
             Trigger("MyTrigger", "timer.GenericCronTrigger", 
                    Configuration({ "cronExpression": "0/10 * * * * ?"}))
        ]
        
    def execute(self, module, input):
        log.debug("JSR223: This is a 'hello world!' from a Jython rule (raw API): Cron")

automationManager.addRule(MyRule())
```

**Comment by sim0nx** [comment] 2018-10-06 20:00
I have upgraded OH to the latest milestone release and updated this repo.

Now I am getting the following error:
> Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/modes.py': TypeError: rule_decorator() takes exactly 1 argument (0 given) in <script> at line number 21

I am using the @rule decorator and "addRule(class())" as in your examples.

**Comment by openhab-5iver** [comment] 2018-10-07 00:10
> I have upgraded OH to the latest milestone release and updated this repo.

Excellent! You're possibly the first, but may be the second person to try out this version! Could you please try supplying a name for the rule? This should be optional though... I'll need to take a look at it. My focus has been on using @rule @when. When I get a minute, I'll drop this in to test...

```
from org.slf4j import Logger, LoggerFactory
from rules import rule
from triggers import CronTrigger

log = LoggerFactory.getLogger("org.eclipse.smarthome.model.script.Rules")

@rule("This is the name of my rule")
class ExtensionCron(SimpleRule):
    def __init__(self):
        self.triggers = [ CronTrigger("0/10 * * * * ?") ]
    
    def execute(self, module, inputs):
        log.debug("JSR223: This is a 'hello world!' from a Jython rule (extension): Cron")
```

**Closed** 2018-10-07 17:35 UTC

**Comment by openhab-5iver** [comment] 2018-10-07 17:40
This should all be fixed now. Please get the latest and try again. 

Also, I've updated the documentation. The format for what you are trying is (tested!)...

```python
from org.slf4j import Logger, LoggerFactory
from openhab.rules import rule
from openhab.triggers import CronTrigger

log = LoggerFactory.getLogger("org.eclipse.smarthome.model.script.Rules")

@rule("This is the name of my rule")
class ExtensionCron(object):
    def __init__(self):
        self.triggers = [ CronTrigger("0/10 * * * * ?").trigger ]
    
    def execute(self, module, inputs):
        log.debug("JSR223: This is a 'hello world!' from a Jython rule (extension): Cron")
```

**Comment by sim0nx** [comment] 2018-10-07 18:09
Great ... spent some time figuring out all the changes (why your example works and my previous did not) but I confirm that it all works smoothly now :-)

Thanks for the quick changes!

**Comment by marcelerkel** [comment] 2018-10-07 18:35
Confirmed working for me as well. Thanks!

**Comment by openhab-5iver** [comment] 2018-10-07 18:55
Thank you both for the feedback! Please also test the rule and trigger decorators... these are the going to be getting the most use.
